CREATE TABLE erp_operating_expenses (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_no            VARCHAR(255) NOT NULL UNIQUE,
  branch_id             UUID REFERENCES erp_branches(id),
  supplier_id           UUID REFERENCES erp_business_partners(id),
  supplier_name_snapshot VARCHAR(255),
  expense_category      VARCHAR(255),
  title                 TEXT,
  document_date         DATE,
  due_date              DATE,
  invoice_status        VARCHAR(50) DEFAULT 'NOT_REQUIRED',
  status                VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  payment_status        VARCHAR(50) NOT NULL DEFAULT 'UNPAID',
  total_amount          NUMERIC(18,2) DEFAULT 0,
  recurrence_type       VARCHAR(50) DEFAULT 'ONE_TIME',
  recurrence_interval   INT DEFAULT 1,
  recurrence_start_date DATE,
  recurrence_end_date   DATE,
  next_due_date         DATE,
  auto_generate_next    BOOLEAN DEFAULT false,
  parent_recurring_id   UUID,
  notes                 TEXT,
  is_deleted            BOOLEAN NOT NULL DEFAULT false,
  created_by            UUID,
  created_at            TIMESTAMP NOT NULL DEFAULT now(),
  updated_at            TIMESTAMP NOT NULL DEFAULT now()
);
